import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;
import 'package:wonderfolio/src/operations.data.gql.dart'
    show
        GAddUserData,
        GAddUserData_insert_users_one,
        GFetchUserListData,
        GFetchUserListData_users,
        GFetchUserListData_users_works,
        GFetchUserListData_users_works_category;
import 'package:wonderfolio/src/operations.req.gql.dart'
    show GAddUserReq, GFetchUserListReq;
import 'package:wonderfolio/src/operations.var.gql.dart'
    show GAddUserVars, GFetchUserListVars;
import 'package:wonderfolio/src/schema.schema.gql.dart'
    show
        GInt_comparison_exp,
        GString_comparison_exp,
        Gcategories_bool_exp,
        Gcategories_constraint,
        Gcategories_inc_input,
        Gcategories_insert_input,
        Gcategories_obj_rel_insert_input,
        Gcategories_on_conflict,
        Gcategories_order_by,
        Gcategories_pk_columns_input,
        Gcategories_select_column,
        Gcategories_set_input,
        Gcategories_update_column,
        Gorder_by,
        Gusers_bool_exp,
        Gusers_constraint,
        Gusers_inc_input,
        Gusers_insert_input,
        Gusers_obj_rel_insert_input,
        Gusers_on_conflict,
        Gusers_order_by,
        Gusers_pk_columns_input,
        Gusers_select_column,
        Gusers_set_input,
        Gusers_update_column,
        Gworks_aggregate_order_by,
        Gworks_arr_rel_insert_input,
        Gworks_avg_order_by,
        Gworks_bool_exp,
        Gworks_constraint,
        Gworks_inc_input,
        Gworks_insert_input,
        Gworks_max_order_by,
        Gworks_min_order_by,
        Gworks_on_conflict,
        Gworks_order_by,
        Gworks_pk_columns_input,
        Gworks_select_column,
        Gworks_set_input,
        Gworks_stddev_order_by,
        Gworks_stddev_pop_order_by,
        Gworks_stddev_samp_order_by,
        Gworks_sum_order_by,
        Gworks_update_column,
        Gworks_var_pop_order_by,
        Gworks_var_samp_order_by,
        Gworks_variance_order_by;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAddUserData,
  GAddUserData_insert_users_one,
  GAddUserReq,
  GAddUserVars,
  GFetchUserListData,
  GFetchUserListData_users,
  GFetchUserListData_users_works,
  GFetchUserListData_users_works_category,
  GFetchUserListReq,
  GFetchUserListVars,
  GInt_comparison_exp,
  GString_comparison_exp,
  Gcategories_bool_exp,
  Gcategories_constraint,
  Gcategories_inc_input,
  Gcategories_insert_input,
  Gcategories_obj_rel_insert_input,
  Gcategories_on_conflict,
  Gcategories_order_by,
  Gcategories_pk_columns_input,
  Gcategories_select_column,
  Gcategories_set_input,
  Gcategories_update_column,
  Gorder_by,
  Gusers_bool_exp,
  Gusers_constraint,
  Gusers_inc_input,
  Gusers_insert_input,
  Gusers_obj_rel_insert_input,
  Gusers_on_conflict,
  Gusers_order_by,
  Gusers_pk_columns_input,
  Gusers_select_column,
  Gusers_set_input,
  Gusers_update_column,
  Gworks_aggregate_order_by,
  Gworks_arr_rel_insert_input,
  Gworks_avg_order_by,
  Gworks_bool_exp,
  Gworks_constraint,
  Gworks_inc_input,
  Gworks_insert_input,
  Gworks_max_order_by,
  Gworks_min_order_by,
  Gworks_on_conflict,
  Gworks_order_by,
  Gworks_pk_columns_input,
  Gworks_select_column,
  Gworks_set_input,
  Gworks_stddev_order_by,
  Gworks_stddev_pop_order_by,
  Gworks_stddev_samp_order_by,
  Gworks_sum_order_by,
  Gworks_update_column,
  Gworks_var_pop_order_by,
  Gworks_var_samp_order_by,
  Gworks_variance_order_by
])
final Serializers serializers = _serializersBuilder.build();
